[package]
name = "tonic-google-protobuf"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = { version = "1" }
tokio = { version = "1", features = ["full"] }
prost = "0.8"
prost-types = "0.8"
tonic = "0.5.1"

[build-dependencies]
tonic-build = "0.5.1"